C6H6_MEASUREMENT_UNIT = ""
CO_MEASUREMENT_UNIT = ""
H2S_MEASUREMENT_UNIT = ""
IPA_MEASUREMENT_UNIT = ""
NO2_MEASUREMENT_UNIT = ""
O3_MEASUREMENT_UNIT = ""
PM10_MEASUREMENT_UNIT = ""
PM2DOT5_MEASUREMENT_UNIT = ""
SO2_MEASUREMENT_UNIT = ""

#TODO fare unità di misura costanti